### ISSUE TITLE
S3 fastq files not reachable

### ISSUE THREAD

**Issue by croct** [wleepang/demo-genomics-workflow-wdl#2]
Hi,

It looks like the example fastq files can't be accessed - AccessDenied.  Has this bucket been made private or moved?

s3://aws-batch-genomics-shared/secondary-analysis/example-files/fastq

**Comment by wleepang** [comment]
Looks that way. I'll look into an alternative.

**Comment by croct** [comment]
I still have the same "AccessDenied" issue.  Was this issue resolved?

**Comment by wleepang** [comment]
I updated the workflow to point to a different input data bucket - [1000Genomes from the Registry of Open Data on AWS](https://registry.opendata.aws/1000-genomes/). If you are running this with Cromwell, make sure you've add the bucket arn (`arn:aws:s3:::1000genomes/*`) to the S3 access policy in the server and AWS Batch job instance roles.

**Comment by croct** [comment]
Thanks
